version: "3"

services:
  app:
    container_name: php
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: volume
        source: php_fpm_socket
        target: /var/run/php-fpm
    restart: always

  web:
    container_name: nginx
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: volume
        source: php_fpm_socket
        target: /var/run/php-fpm
    restart: always
    depends_on:
      - app

  db:
    container_name: mysql
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: volume
        source: mysql_volume
        target: /var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  php_fpm_socket:
  mysql_volume: